# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% #
#             Numbat              # 
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% #
library(optparse)
parser = OptionParser(description='Execute Numbat')
parser = add_option(parser, '--rootDir', default = "/your/local/path/to/repo/", type = "character")
parser = add_option(parser, '--sampleID', default = "toy_data", type = "character")
parser = add_option(parser, '--refPath', default = "", type = "character")
parser = add_option(parser, '--refannoPath', default = "Annotation.txt", type = "character")
parser = add_option(parser, '--refOrgan', default = "Stomach_cDNA", type = "character")
args <- parse_args(parser)

library(numbat)
library(Seurat)
library(data.table)
root_Dir <- args$rootDir
sample_id <-args$sampleID
ref_Path <- args$refPath
refanno <- args$refannoPath
refOrgan <- args$refOrgan
input_Dir <- paste0(root_Dir, "data/", sample_id, "/filtered_feature_bc_matrix")
Out_Dir <- paste0(root_Dir, "Result/", sample_id, "/Numbat/")

dir.create(Out_Dir, showWarnings = FALSE, recursive = TRUE)
setwd(Out_Dir)
message("Method: Numbat ...")
message("Process ", sample_id, " ...")
message("Output Directory: ", Out_Dir)
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% #
#           Input data            # 
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% #
input_expr <- Read10X(data.dir = input_Dir)
ref_expr <- as.matrix(read.csv(ref_Path, row.names = 1))
colnames(ref_expr) <- gsub("[.]", "-", colnames(ref_expr))

ref_cell_type <- read.delim(refanno, header = TRUE, row.names = 1)
ref_cell_type <- ref_cell_type[ref_cell_type$orig.ident == refOrgan,]
rownames(ref_cell_type) <- gsub(paste0(refOrgan, "_"), "", rownames(ref_cell_type))
ref_cell_type <- ref_cell_type[colnames(ref_expr),]
table(ref_cell_type$Cell_type_in_each_tissue)
ref_anno <- data.frame(cell = rownames(ref_cell_type),
                       group = ref_cell_type$Cell_type_in_each_tissue)
ref_aggr <- aggregate_counts(ref_expr, ref_anno)

alle <- as.data.frame(fread(paste0(Out_Dir, sample_id, '_allele_counts.tsv.gz')))

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% #
#            Execute              # 
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% #
out <- run_numbat(
  input_expr, # gene x cell integer UMI count matrix 
  ref_aggr, # reference expression profile
  alle, # allele data.frame generated by pileup_and_phase script
  genome = "hg38",
  t = 1e-5,
  ncores = 10,
  plot = TRUE,
  call_clonal_loh = TRUE,
  out_dir = Out_Dir
)
